version: "3"

services:
  gis:
    ports:
      - 5432:5432
    image: mdillon/postgis
    deploy:
      replicas: 1
    environment:
      POSTGRES_DB: "gis"
      POSTGRES_PASSWORD: "mgggiskool"
      POSTGRES_USER: "mggg"
      ALLOW_IP_RANGE: "0.0.0.0/0"
  api:
    image: mggg/districtr-api
    ports:
      - 3000:3000
