version: "3.5"

# This compose file is for deployment with `docker stack deploy`
# The main difference between docker-compose.yml and this file is
# that we create a volume on the host to persist the database.

# We use the mggg/districtr-api:31 container here as an example.
# When deploying, replace "31" with the tag of the build that you
# want to deploy.

# You will need to provide files `secret_key`, `gis_user`, and
# `gis_password` holding the secrets needed to run the api.

services:
  gis:
    image: mdillon/postgis:11
    deploy:
      replicas: 1
    environment:
      POSTGRES_DB: "gis"
      POSTGRES_PASSWORD_FILE: "/run/secrets/gis_password"
      POSTGRES_USER_FILE: "/run/secrets/gis_user"
      ALLOW_IP_RANGE: "0.0.0.0/0"
    volumes:
      - /data/volumes/gis:/var/lib/postgresql
    secrets:
      - gis_user
      - gis_password
  api:
    image: mggg/districtr-api:31
    environment:
      POSTGRES_DB: "gis"
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: "gis"
    ports:
      - "3000:3000"
    depends_on:
      - gis
    deploy:
      replicas: 2
    secrets:
      - secret_key
      - gis_user
      - gis_password

secrets:
  secret_key:
    file: ./secret_key
  gis_user:
    file: ./gis_user
  gis_password:
    file: ./gis_password
